application: image-proxy
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /crossdomain.xml
  static_files: crossdomain.xml
  upload: crossdomain.xml

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: favicon.png
  upload: favicon.png

- url: /.*
  script: main.py